export const mapStyle = {
  countryBoundary: {
    id: "output_country-2uwmmw",
    minzoom: 0,
    maxzoom: 22,
    type: "line",
    paint: {
      "line-opacity": 1,
    },
    source: "composite",
    "source-layer": "output_country-0xvogw",
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
  },
  projectClusters: {
    circles: {
      id: "projectClusters-circles",
      type: "circle",
      source: "projectClusters",
      paint: {
        "circle-color": [
          "interpolate",
          ["exponential", 1],
          ["get", "countProjects"],
          0,
          "hsl(295, 78%, 73%)",
          10,
          "hsl(284, 79%, 71%)",
          20,
          "hsl(274, 82%, 70%)",
          40,
          "hsl(266, 83%, 68%)",
          60,
          "hsl(257, 84%, 66%)",
          80,
          "hsl(248, 85%, 64%)",
          100,
          "hsl(235, 86%, 60%)",
        ],
        "circle-stroke-color": [
          "interpolate",
          ["exponential", 1],
          ["get", "countProjects"],
          0,
          "hsl(295, 78%, 51%)",
          10,
          "hsl(284, 79%, 50%)",
          20,
          "hsl(274, 82%, 49%)",
          40,
          "hsl(266, 83%, 48%)",
          60,
          "hsl(257, 84%, 46%)",
          80,
          "hsl(248, 85%, 45%)",
          100,
          "hsl(235, 86%, 42%)",
        ],
        "circle-stroke-width": 0.75,
        "circle-radius": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          [
            "*",
            [
              "interpolate",
              ["exponential", 1],
              ["get", "countProjects"],
              0,
              3,
              10,
              6,
              20,
              9,
              40,
              12,
              60,
              15,
              80,
              18,
              100,
              21,
            ],
            2.7,
          ],
          5,
          [
            "*",
            [
              "interpolate",
              ["exponential", 1],
              ["get", "countProjects"],
              0,
              3,
              10,
              6,
              20,
              9,
              40,
              12,
              60,
              15,
              80,
              18,
              100,
              21,
            ],
            2.9700000000000006,
          ],
          10,
          [
            "*",
            [
              "interpolate",
              ["exponential", 1],
              ["get", "countProjects"],
              0,
              3,
              10,
              6,
              20,
              9,
              40,
              12,
              60,
              15,
              80,
              18,
              100,
              21,
            ],
            3.78,
          ],
          22,
          [
            "*",
            [
              "interpolate",
              ["exponential", 1],
              ["get", "countProjects"],
              0,
              3,
              10,
              6,
              20,
              9,
              40,
              12,
              60,
              15,
              80,
              18,
              100,
              21,
            ],
            5.4,
          ],
        ],
      },
    },
    labels: {
      id: "projectClusters-labels",
      type: "symbol",
      source: "projectClusters",
      layout: {
        "text-field": ["to-string", ["get", "countProjects"]],
        "text-font": ["Open Sans Bold"],
        "text-size": 12,
      },
    }
  },
  socialProtection: {
    Level1: {
      "id": "output-level1-sp-6xybr6",
      "maxzoom": 6,
      "type": "fill",
      "layout": {},
      "source": "Level1",
      "source-layer": "output_level1_sp-6xybr6",
      "paint": {
        "fill-pattern": "stripe3",
        "fill-opacity": 0.2
      }},
    Level2: {
      "id": "output-level2-sp-9olbf0",
      "minzoom": 6,
      "type": "fill",
      "paint": {
        "fill-pattern": "stripe3",
        "fill-opacity": 0.2
      },
      "layout": {},
      "source": "Level2",
      "source-layer": "output_level2_sp-9olbf0"
    },
  }
}