/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:af390252-6ed5-48b5-a60d-63c764fc4947",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_whSr0DXZR",
    "aws_user_pools_web_client_id": "79f6k4euu46e2d80j06tm4paat",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "foodsecurity-assets-public",
    "aws_user_files_s3_bucket_region": "eu-north-1",
    "aws_cloud_logic_custom": [
        {
            "name": "documentsAPI",
            "endpoint": "https://85l9ol9rnb.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;
